name: REMOTE
on: [commit_comment]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Hello, world!
      env:
        GITHUB_ACTOR: ${{ github.ACTOR }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        echo hello worlds
